# Dockerize Predix Machine on Predix Machine DTR Alpine

# Copyright (c) 2012-2016 General Electric Company. All rights reserved."
# The copyright to the computer software herein is the property of"
# General Electric Company. The software may be used and/or copied only"
# with the written permission of General Electric Company or in accordance"
# with the terms and conditions stipulated in the agreement/contract"
# under which the software has been supplied"

FROM dtr-alpha.gear.ge.com/predixmachine/openjdk-jre-x86_64:7u91-alpine3.3
MAINTAINER Predix Machine Team

# Install bash and tzdata packages as the base image no longer includes these.
RUN apk update && \
    apk add bash tzdata

# Run Parameters
ARG MACHINE_DIR=./PredixMachine

# Copy Machine onto image
COPY $MACHINE_DIR /PredixMachine

# data directory that will be mapped to a volume on host
ENV PREDIX_MACHINE_DATA_DIR /data
ENV PREDIX_MACHINE_DOCKER_ENABLED true

# Start Predix Machine when container starts. This script sets up machine to use /data 
# for appdata, configuration, logs and security folders before starting Predix Machine
COPY docker_start_predixmachine.sh /PredixMachine/bin/
ENTRYPOINT ["/bin/sh", "-c", "/PredixMachine/bin/docker_start_predixmachine.sh" ]


# Inform docker that our container is listening on 8443 - the HTTPS server in Predix Machine
# Docker is smart will map this to some port on the host machine. You can control that with 
# the -P option of the 'docker run' command. It makes it possible to run multiple Predix Machine 
# instances, each internally configured to say 8443 but mapped to different ports on the host 
# machine.
EXPOSE 8443